spring:
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/my_db
    username: bestuser
    password: bestuser
  flyway:
    baseline-on-migrate: true
  main:
    allow-circular-references: true